version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"                # donde vive tu pyproject.toml
    schedule:
      interval: "daily"
      time: "02:00"               # hora UTC
    open-pull-requests-limit: 5

    # Grupos válidos (solo se permiten 'patterns' y/o 'exclude')
    groups:
      security-updates:
        patterns:
          - "*"
      routine-updates:
        patterns:
          - "*"
        exclude:
          - "pip"                 # evita PRs para pip en sí mismo
