name: python-tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: {}

jobs:
  test-rep-export-windows:
    name: Windows / Python 3.9
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests for rep-export-Windows
        working-directory: rep-export-Windows
        run: pytest ../test-rep-export-Windows --maxfail=1 --disable-warnings -q

  test-rep-export-linux-mac:
    name: Linux / Python 3.9
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests for rep-export-LINUXandMAC
        working-directory: rep-export-LINUXandMAC
        run: pytest ../test-rep-export-LINUXandMAC --maxfail=1 --disable-warnings -q
