name: CI - Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test:
    name: Run all tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.9', '3.10', '3.11' ]

    steps:
      # 1) Checkout código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Configurar Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # 3) Instalar proyecto + extras (dev, gitignore)
      - name: Install project with dev & gitignore extras
        run: |
          python -m pip install --upgrade pip
          # Instala en editable con extras; incluye pytest y pathspec
          pip install ".[dev,gitignore]"

      # 4) Ejecutar tests
      - name: Run pytest
        run: pytest tests --maxfail=1 --disable-warnings -q
